import type { Metadata } from 'next';
import { UserProvider } from '@auth0/nextjs-auth0/client';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <main>{children}</main>
        </body>
      </UserProvider>
    </html>
  );
}
